baseURL = "https://dangen-effy.github.io/"
languageCode = "ko-kr"
paginate = 5
title = "ì†ë‹¹ê·¼ ê°œë°œ ë¸”ë¡œê·¸"
enableEmoji = true
theme = "hugo-theme-yinyang"
defaultContentLanguage = "ko"

[author]
  name = "Sohn Dangen"
  homepage = "https://dangen-effy.github.io/"

[params]
headTitle = "ğŸ¥•ì„±ê³µí•œ ì Šì€ì´"
description = "ìë°”ìŠ¤í¬ë¦½íŠ¸, ë°ë¸Œì˜µìŠ¤, ë°±ì—”ë“œ, ê°œë°œ, Node.js, JavaScript, DevOps, Docker"
disqus = "sohn-dangen-blog"
extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-158927245-1"></script>'
favicon = "/favicon.ico"
location = "Seoul, Korea"

[[params.socials]]
name = "Me"
link = "https://www.youtube.com/channel/UC7hYsleeRIUjlBz2LJRCbuQ"
[[params.socials]]
name = "GitHub"
link = "https://github.com/dangen-effy"
[[params.socials]]
name = "RSS"
link = "/index.xml"
