baseURL = "https://dangen-effy.github.io/"
languageCode = "ko-kr"
paginate = 5
title = "ì†ë‹¹ê·¼ ê°œë°œ ë¸”ë¡œê·¸"
enableEmoji = true
theme = "hugo-theme-yinyang"
defaultContentLanguage = "ko"
enableRobotsTXT = true
[author]
  name = "Sohn Dangen"
  homepage = "https://dangen-effy.github.io/"

[params]
mainSections = ["post"]
headTitle = "ğŸ¥•ì„±ê³µí•œ ì Šì€ì´"
description = "ì†ë‹¹ê·¼ì˜ ë¸”ë¡œê·¸"
disqus = "sohn-dangen-blog"
extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-158927245-1"></script>'
favicon = "/favicon.ico"
location = "Seoul, Korea"
images = ["dangen.png"]

[[params.socials]]
name = "Me"
link = "https://dangen-effy.github.io/about"
[[params.socials]]
name = "RSS"
link = "/index.xml"

[markup.goldmark.renderer]
unsafe = true